import "server-only";

import webpush from "web-push";

import { createAdminClient } from "@/lib/supabase/admin";

import type { ChannelAdapter, OutgoingMessage, SendOutcome } from "../types";

/**
 * Web Push, self-issued.
 *
 * `push` has been a value of `notification_channel` since the schema was
 * written, with nothing behind it. This is the adapter, and it is the one push
 * mechanism that needs no vendor account: VAPID keys are generated by us, so
 * there is no third party between a salon and its own phone.
 *
 * A subscription is a capability - whoever holds the endpoint can push to that
 * device - so the rows are read here with the service role and never leave the
 * server.
 */
export const webPushChannel: ChannelAdapter = {
  channel: "push",
  provider: "web-push",

  isConfigured() {
    return Boolean(
      process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY,
    );
  },

  async send(message: OutgoingMessage): Promise<SendOutcome> {
    if (!message.profileId) {
      return { ok: false, error: "no_profile", retryable: false };
    }

    webpush.setVapidDetails(
      process.env.VAPID_SUBJECT ?? "mailto:hello@glowa.bg",
      process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY!,
      process.env.VAPID_PRIVATE_KEY!,
    );

    const supabase = createAdminClient();
    const { data: subscriptions } = await supabase
      .from("push_subscriptions")
      .select("id, endpoint, p256dh, auth")
      .eq("profile_id", message.profileId);

    if (!subscriptions || subscriptions.length === 0) {
      // Nothing subscribed is not a failure of this send; it is a person who
      // never turned push on.
      return { ok: false, error: "no_subscription", retryable: false };
    }

    const payload = JSON.stringify({
      title: message.subject,
      // A push body is a glance, not an email. Keep it to the first line.
      body: message.text.split("\n").find((line) => line.trim()) ?? "",
      locale: message.locale,
      tag: message.idempotencyKey,
      url: message.url ?? `/${message.locale}/bookings`,
    });

    let delivered = 0;
    const gone: string[] = [];
    let lastError = "";

    for (const subscription of subscriptions) {
      try {
        await webpush.sendNotification(
          {
            endpoint: subscription.endpoint,
            keys: { p256dh: subscription.p256dh, auth: subscription.auth },
          },
          payload,
          { TTL: 60 * 60 * 12 },
        );
        delivered += 1;
      } catch (cause) {
        const status = (cause as { statusCode?: number })?.statusCode;
        // 404/410 mean the browser threw the subscription away. Keeping it
        // would mean retrying a dead endpoint forever.
        if (status === 404 || status === 410) {
          gone.push(subscription.id);
        } else {
          lastError = `push_${status ?? "error"}`;
        }
      }
    }

    if (gone.length > 0) {
      await supabase.from("push_subscriptions").delete().in("id", gone);
    }

    if (delivered > 0) {
      await supabase
        .from("push_subscriptions")
        .update({ last_used_at: new Date().toISOString() })
        .eq("profile_id", message.profileId);
      return { ok: true, providerMessageId: null };
    }

    // Every endpoint was expired: there is nothing to retry against.
    if (gone.length > 0 && !lastError) {
      return { ok: false, error: "subscription_expired", retryable: false };
    }

    return { ok: false, error: lastError || "push_failed", retryable: true };
  },
};

/** The key the browser needs to subscribe. Public by design. */
export function vapidPublicKey() {
  return process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY ?? null;
}
